# Generated by Django 5.2.15 on 2026-07-02 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Monster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("level", models.IntegerField(default=1)),
                ("health", models.IntegerField(default=50)),
                ("attack", models.IntegerField(default=10)),
                ("defense", models.IntegerField(default=5)),
                ("is_boss", models.BooleanField(default=False)),
                ("experience_reward", models.IntegerField(default=20)),
            ],
        ),
        migrations.CreateModel(
            name="LootDrop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("drop_chance", models.FloatField(default=0.1)),
                ("min_quantity", models.IntegerField(default=1)),
                ("max_quantity", models.IntegerField(default=1)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="characters.item",
                    ),
                ),
                (
                    "monster",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loot_table",
                        to="characters.monster",
                    ),
                ),
            ],
        ),
    ]
