# Generated by Django 5.2.15 on 2026-07-01 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_task_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="show",
            field=models.BooleanField(default=True),
        ),
    ]
